version: '3.3'

services:
  app:
    build:
      context: .
    env_file: .env
    ports:
      - "80:80"
      - "3000:3000"
      - "5000:5000"
    restart: always
    volumes:
     - .:/var/www/html:delegated
